---
  title: "machine learning(732A99) lab1 optional tasks"
author: "Anubhav Dikshit(anudi287)"
date: "26 November 2018"
output: 
  pdf_document:
  toc: true
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 1

## Loading The Libraries
```{r, message=FALSE, echo = FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(xlsx, kknn, caret)

options(scipen = 999)

```

## Loading Input files
```{r}
spam_data <- read.xlsx("spambase.xlsx", sheetName = "spambase_data")

set.seed(12345)

n =  NROW(spam_data)
id = sample(1:n, floor(n*0.5))
train = spam_data[id,]
test = spam_data[-id,]
```


## 1.5 Repeat step 4 for K=1 and compare the results with step 4. What effect does the decrease of K lead to and why?
```{r}
knn_model1 <- train.kknn(Spam ~., data = train, kmax = 30)

train$knn_prediction_class <- predict(knn_model1, train)
test$knn_prediction_class <- predict(knn_model1, test)

conf_train2 <- table(train$Spam, train$knn_prediction_class)
names(dimnames(conf_train2)) <- c("Actual Train", "Predicted Train")
confusionMatrix(conf_train2)

conf_test2 <- table(test$Spam, test$knn_prediction_class)
names(dimnames(conf_test2)) <- c("Actual Test", "Predicted Test")
confusionMatrix(conf_test2)
```

## Function for distance
```{r}

cosine <- function(A, B){
dem <- 1 / sqrt(rowSums(A * B))
num <- A %*% t(B)
answer <-  1 - (num/dem)
}



knearest <- function(data, K, newdata){

  data$ID <- rownames(data)
  newdata$ID <- rownames(newdata)
  
  
  
}







n =  NROW(spam_data)
id = sample(1:n, floor(n*0.5))
train = spam_data[id,]
test = spam_data[-id,]


try <- knearest(train, test, 49, K=30)

```

# Appendix
```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```