---
title: "machine learning(732A99) lab2 block2"
author: "Anubhav Dikshit(anudi287)"
date: "17 December 2018"
output: 
    pdf_document:
      toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Assignment 1

## Loading The Libraries
```{r, message=FALSE, echo = TRUE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(xlsx, ggplot2, MASS, tidyr, dplyr, reshape2, gridExtra, 
               tree, caret, e1071, pROC, boot, factoextra)

set.seed(12345)
options("jtools-digits" = 2, scipen = 999)
```

##1. Use time series plots to visually inspect how the mortality and influenza number vary with time (use Time as X axis). By using this plot, comment how the amounts of influenza cases are related to mortality rates.

```{r}
set.seed(12345)

# Importing data
flu_data = read.xlsx("influenza.xlsx", sheetName = "Raw data")

ggplot(flu_data, aes(x=Time, y = Influenza)) + geom_line()

```


# Appendix
```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```